name: 'r-workflows'
description: 'Test, document, and deploy R packages.'
author: 'Brian M. Schilder'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.PAT_GITHUB }}'
    default: ${{ secrets.PAT_GITHUB }}
  run_bioccheck:
    description: "Run Bioconductor checks. Must pass in order to continue workflow."
    default: 'true'
  run_crancheck:
    description: "Run CRAN checks. Must pass in order to continue workflow."
    default: 'true'
  has_testthat:
    description: "Run unit tests and report results."
    default: 'true'
  run_covr:
    description: "Run code coverage tests and publish results to codecov."
    default: 'true'
  run_pkgdown:
    description: "Knit the README.Rmd (if available), build documentation website, and deploy to gh-pages branch."
    default: 'true'
  has_RUnit: 
    description: "Run R Unit tests."
    default: 'false'
  cache-version: 
    description: "Which cache version to use."
    default: 'cache-v1'
  run_docker: 
    description: "Whether to build and push a Docker container to DockerHub."
    default: 'false' 
  DOCKER_USERNAME: 
    description: "DockerHub username." 
    default: ''
  DOCKER_ORG: 
    description: "DockerHub organization name." 
    default: 'neurogenomicslab'
  DOCKER_TOKEN:
    description: "DockerHub token."
    default: ${{ secrets.DOCKER_TOKEN }}
runs:
  using: 'composite'
  steps: 
    - uses: ./.github/actions/check-bioc-docker.yml
    
    