name: 'build-docker'
description: >
  rworkflows: Build a Docker container and push it to DockerHub.
author: 'Brian M. Schilder'
inputs: 
  i:
    description: >
      A list of inputs from the controller workflow.
runs:
  using: 'composite'    
  steps:
    - name: Set GitHub token 
      run: |
        echo "GITHUB_PAT=${{ inputs.i.GITHUB_TOKEN }}" >> $GITHUB_ENV 
        echo "GITHUB_TOKEN=${{ inputs.i.GITHUB_TOKEN }}" >> $GITHUB_ENV 
        echo "DOCKER_TOKEN=${{ inputs.i.DOCKER_TOKEN }}" >> $GITHUB_ENV  
      shell: bash {0} 

    - name: Get R package info
      if: inputs.i.runner_os == 'Linux'
      run: |
        #### DockerHub repos must be lowercase (,,) ####
        name=$(grep '^Package:' DESCRIPTION | cut -d\   -f2)
        echo "packageName=${name,,}" >> $GITHUB_ENV
        echo "packageNameOrig=${name}" >> $GITHUB_ENV
        echo $name
        version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
        echo "packageVersion=${version}" >> $GITHUB_ENV
        echo $version
      shell: bash {0} 
        
    ## DockerHub steps
    - name: Create Docker file
      if: "(!contains(github.event.head_commit.message, '/nodocker')) && inputs.i.run_docker == 'true' && inputs.i.runner_os == 'Linux'"
      run: |
        options(crayon.enabled = TRUE)
        if(!require("rworkflows")) remotes::install_github("neurogenomics/rworkflows")
        path <- rworkflows::use_dockerfile()
      shell: Rscript {0} 
      
    - name: Build and push to DockerHub
      if: "(!contains(github.event.head_commit.message, '/nodocker')) && inputs.i.run_docker == 'true' && inputs.i.runner_os == 'Linux'"
      uses: docker/build-push-action@v1
      with:
        username: ${{ inputs.i.docker_user }}
        password: ${{ env.DOCKER_TOKEN }}
        repository: ${{ inputs.i.docker_org }}/${{ env.packageName }}
        tag_with_ref: true
        tag_with_sha: false
        tags: ${{ env.packageVersion }},latest
        build_args: PKG=${{ env.packageNameOrig }}
