name: rworkflows
'on':
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main
jobs:
  rworkflows:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: no
      matrix:
        config:
        - os: ubuntu-latest
          r: devel
          bioc: devel
          cont: bioconductor/bioconductor_docker:devel
          rspm: https://packagemanager.rstudio.com/cran/__linux__/focal/release
        - os: macOS-latest
          r: latest
          bioc: release
        - os: windows-latest
          r: latest
          bioc: release
    steps:
    - if: ${{ env.ACT }}
      name: Hack container for local development
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
      shell: bash {0}
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: no
        run_crancheck: yes
        run_vignettes: yes
        has_testthat: yes
        run_covr: yes
        run_pkgdown: yes
        has_runit: no
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run_docker: yes
        DOCKER_USERNAME: bschilder
        DOCKER_ORG: neurogenomicslab
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
