name: r_workflows test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    name: r_workflows test  
    env: 
      R_KEEP_PKG_SOURCE: yes 
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # RSPM: ${{ matrix.config.rspm }}
      NOT_CRAN: true
      TZ: UTC 
      RGL_USE_NULL: TRUE  
      
    steps:
      - uses: actions/checkout@v3
      - uses: ./test-document-deploy
        with:  
            run_bioccheck: 'false'
            run_crancheck: 'true'
            has_testthat: 'true'
            run_covr: 'true'
            run_pkgdown: 'true'
            has_RUnit: 'true'
            run_docker: 'true' 
            repository: ${{ github.repository }}
            repo-token: ${{ secrets.PAT_GITHUB }}
            DOCKER_USERNAME: 'bschilder'
            DOCKER_ORG: 'neurogenomicslab'
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
