name: r_workflows test

on: [workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:  
            - uses: neurogenomics/r_workflows@latest
            with:
                run_bioccheck: 'false'
                run_crancheck: 'true'
                has_testthat: 'true'
                run_covr: 'true'
                run_pkgdown: 'true'
                has_RUnit: 'true'
                run_docker: 'true'
                DOCKER_USERNAME: 'bschilder'
                DOCKER_ORG: 'neurogenomicslab'
