name: test-document-deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-document-deploy:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    shell: bash
    ## Environment variables unique to this job.

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: 'devel', bioc: 'devel', cont: "bioconductor/bioconductor_docker:devel", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/release"}
          - { os: macOS-latest, r: 'latest', bioc: 'release'}
          - { os: windows-latest, r: 'latest', bioc: 'release'}
          ## Check https://github.com/r-lib/actions/tree/master/examples
          ## for examples using the http-user-agent 
    env: 
      R_KEEP_PKG_SOURCE: yes 
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      NOT_CRAN: true
      TZ: UTC 
      RGL_USE_NULL: TRUE  
      
    steps: 
      - if: ${{ env.ACT }}
        name: Hack container for local development
        run: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - uses: actions/checkout@v3
      - uses: ./test-document-deploy
        with:  
            run_bioccheck: 'false'
            run_crancheck: 'true'
            has_testthat: 'true'
            run_covr: 'true'
            run_pkgdown: 'true'
            has_RUnit: 'true'
            run_docker: 'true' 
            repository: ${{ github.repository }}
            repo-token: ${{ secrets.PAT_GITHUB }}
            DOCKER_USERNAME: 'bschilder'
            DOCKER_ORG: 'neurogenomicslab'
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
