name: r_workflows test

on: [workflow_dispatch]

jobs:
    test:
        steps: 
            - uses: neurogenomics/r_workflows@latest
            name: Run r_workflows
            with: 
                run_bioccheck: 'true'
                run_crancheck: 'true'
                run_docker: 'false'
                DOCKER_USERNAME: 'bschilder'
                DOCKER_ORG: 'neurogenomicslab'
                repository: 'neurogenomics/templateR'
